Create server with NodeJs and express
Chen-Abudi/tic-tac-toe pull request #1
Opened 2023-02-03 14:10 UTC by tamerjb

2023-02-07 17:25 UTC, yonatanAiz requested changes
Please delete autogenerated files, DS_Store

2023-02-07 17:25 UTC, yonatanAiz commented on packages/server/index.js
> +const { MONGODB_URI = 'mongodb://localhost:27017/tictac' } = process.env;
Please destructure both MONGODB_URI and PORT from same line

```suggestion
const { MONGODB_URI = 'mongodb://localhost:27017/tictac', PORT = 3000 } = process.env;
```

2023-02-07 17:25 UTC, yonatanAiz commented on packages/server/index.js
> +    });
Fix indentation

2023-02-07 17:26 UTC, yonatanAiz approved these changes

2023-02-14 19:46 UTC, Chen-Abudi approved these changes
Nice thanks !

2023-02-14 19:48 UTC, merged